/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 01.05.2026 22:28:09

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 4464;
#else
constexpr int kTensorArenaSize = 3440;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,1287 } };
const TfArray<1, float> quant0_scale = { 1, { 0.056779898703098297, } };
const TfArray<1, int> quant0_zero = { 1, { -3 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[8] = { -2065, -474, -1004, 605, 1550, 535, 412, -297, };
const TfArray<1, int> tensor_dimension6 = { 1, { 8 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00030607028747908771, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[8*400] = { 
  -39, -68, -15, -60, -26, -1, -42, 25, 57, -55, 32, -41, 1, -17, -1, 9, -36, -38, -68, -20, -39, 4, -34, -18, 13, -22, 23, 0, 2, -13, -23, -30, -30, -39, -65, 40, -70, 1, -49, -40, 8, -34, 12, 38, -17, -4, -10, -2, -38, 1, 10, -43, -20, -30, -6, -38, 31, -56, -23, 27, 22, 1, -6, 18, 13, 25, -23, -59, -21, -15, 14, -12, 65, -14, 37, 26, -15, 10, -21, 59, -32, -38, 12, -15, -37, -4, 38, -68, 14, -6, 30, 31, -15, -30, 8, 56, -48, 1, 22, -54, -66, -10, 21, -94, 21, -23, 29, 19, -12, -18, -3, 45, -51, 21, 5, -20, -63, -10, 9, -25, 18, -16, 17, 30, -38, -1, -2, 20, -46, -8, 23, -18, -51, 15, 41, -52, 19, -22, 7, 16, -39, -16, -20, 29, 13, 29, -25, -36, -50, 4, 1, -28, 32, -17, 10, 43, -16, -5, -20, 23, -43, -1, -6, -28, -63, -17, 7, -42, 11, 3, 7, 2, -10, -9, 12, 30, -19, 7, 5, -25, -49, -11, 27, -22, 33, -16, 7, 34, -28, 14, -6, 34, -19, -4, 0, -15, -49, 6, 34, -24, 26, 17, 18, 37, 24, 3, -4, 43, -6, -24, -6, -14, -73, -1, 45, -52, 12, 13, 22, 39, -9, 9, -10, 37, -2, 20, -5, -14, -20, 14, 18, -41, 49, 16, 24, 34, 3, 28, 17, 32, -6, -32, -7, -19, -61, 0, 37, -57, 10, -18, 13, 26, 13, 16, -15, 38, -7, -14, -38, -51, -42, 10, 16, -77, 40, 2, 19, 18, -12, 1, -26, 40, 7, 13, -12, -44, -49, -19, 12, -48, 30, 9, 29, 20, -1, 1, -15, 18, 2, 1, 1, -101, -67, 21, 11, -59, 41, 1, 19, 11, -5, 0, -43, 45, -5, 14, 14, -127, -22, 2, 12, -59, 47, -35, 32, 25, 28, -3, -20, 30, -26, 21, 8, -50, -8, 19, 22, -65, 36, -10, 46, -32, 18, 1, -70, 37, 13, -3, -44, -78, -14, 16, -11, -73, 39, -22, 38, -83, -23, 16, -75, 43, -10, -13, 12, -77, -38, 3, 9, -37, 29, 1, 18, 5, -7, -6, -67, 33, 14, -49, -17, -67, -16, 29, 19, -40, 26, -23, 39, -47, 20, 9, -15, 38, 4, 3, -50, -103, -34, 9, -31, -36, 1, -45, 8, -38, 40, -20, -13, -1, 
  62, -16, -13, 10, -7, 28, 7, -22, 44, 3, -5, -5, 44, -15, 13, -10, 52, -4, 14, 24, -45, 17, -19, -3, 35, -8, 10, 8, 12, -32, 14, 3, -4, -14, 8, 42, 1, 4, -46, 16, 30, -16, 9, -1, -9, -70, 11, -13, 28, -15, -17, 27, -23, 8, -41, 8, 16, -6, 23, 26, -9, -32, -1, -4, 26, -68, 8, 44, -39, 5, -33, 10, 34, 8, 30, 42, 9, -75, 1, 33, 8, -55, 9, 52, -29, 7, -47, 25, 46, -8, 23, 12, 38, -40, 25, -18, 15, -30, 17, 30, -24, 24, -28, 12, 15, -39, 24, 18, 18, -45, -1, -7, 11, -41, 16, 26, -17, 6, -61, 27, 18, -15, -1, 11, 15, -53, 20, 0, 16, 1, -3, 39, -10, 3, -40, -15, 17, -19, 16, 20, 48, -64, 32, 4, 37, -24, 3, 42, 8, 6, -51, 1, 1, -35, 15, 16, 4, -45, 15, 3, 30, -43, 7, 32, -35, 5, -41, -5, -6, -49, 7, 30, 31, -53, 9, -19, -27, -37, -13, 54, -6, 30, 9, 6, -14, -25, 22, 28, 37, -84, 11, 21, -3, -13, 4, 25, -5, 26, -46, 9, -3, -10, 11, 35, 17, -96, 25, 15, 21, -40, 8, 47, 9, 15, -36, -16, 8, -37, 17, 33, 30, -34, 16, -23, 7, -24, -11, 28, 2, 23, -9, 22, -1, -2, 24, 29, 16, -50, 17, 3, 27, -41, -34, 13, -10, 3, -40, 4, 17, 1, 15, 18, 21, -49, 5, -5, 30, 7, -7, 28, -32, 15, -18, -18, 8, -9, 39, 19, -19, -19, 4, 1, 7, -45, -6, 13, 22, 12, -27, 37, -13, -21, 18, 27, -7, -56, 22, -24, -3, -29, 14, 28, -2, 21, -28, -15, -11, -25, 36, 24, 32, -37, 29, 2, 3, -7, -18, 5, 15, 6, -67, 5, -32, -47, 48, 23, -14, -17, -4, -53, -25, -87, 16, -35, 18, 3, -9, -3, -17, 14, 53, 29, 30, -89, -18, -10, -30, -1, -5, 54, -2, 22, -19, -24, -43, -25, 38, 23, 32, -54, -29, -25, -7, -14, -26, -1, 3, -10, 5, 9, -19, -27, 20, 19, -16, -53, -1, -23, -13, -26, 3, 5, -10, 8, -19, 6, -31, -4, 44, 19, 23, -51, 0, 6, -3, -5, 36, 24, 14, -2, -48, 20, -46, -13, 27, 20, -8, -90, -33, -77, 
  16, 17, 46, 60, -21, 27, 13, 3, 2, -22, 16, 60, -7, 26, 15, -50, -10, -4, -3, 28, -69, 18, 3, -32, 28, 2, 20, 18, 2, 39, -14, -55, -6, 45, 34, 23, -63, 21, 11, -19, 14, -34, 13, 27, 32, 24, -2, -21, -49, 2, 8, 17, -36, 23, -27, 23, 7, 14, 32, 29, -15, 22, 14, -48, -2, -3, 38, 29, -68, 8, -11, -5, 3, -64, 5, 32, -12, 21, 14, -60, -21, 14, 26, 29, -51, 29, -46, -12, 28, -54, 31, 31, 21, 38, -10, -47, -27, 12, 35, 21, -42, 22, -28, -2, 15, -34, 7, 9, -19, 17, 6, -34, -2, 19, 10, -7, -67, 42, -15, -25, 37, -33, 24, 47, 23, 20, 1, -35, 11, 4, 14, 10, -69, 34, -2, -12, 9, -30, 26, 30, -7, 27, -9, -12, -52, -4, 7, 25, -76, 26, -12, -17, 6, -60, 3, 43, -24, 38, 35, -36, -20, 5, 30, 27, -59, 28, -42, -34, 22, -45, 31, 33, 9, 24, 4, -17, -13, 3, 12, 17, -59, 21, -39, -23, 22, -46, -1, 22, -2, 26, -7, -48, -9, -3, 8, 23, -96, 26, -10, -13, 25, -72, 2, 38, 1, 36, 1, -36, -8, 24, 20, -14, -13, 38, -12, -16, 16, -21, 5, 0, 10, 8, -20, -13, -32, 21, 14, 20, -34, 24, -19, -22, 33, -25, -6, 23, -21, 24, -15, -24, -50, 12, 12, 10, -53, 34, -26, -12, 29, -34, 14, 13, 16, 15, -27, -23, -18, 17, 9, 4, -38, 24, -56, 18, 18, -40, 4, 21, -12, 11, -11, -43, -16, 19, 25, 15, -42, 26, -18, 8, 28, -27, -5, 20, -8, 21, 12, -31, 18, 31, -4, -2, -35, 30, -26, -5, 26, -67, -18, 8, -2, 11, -1, -36, 8, 6, -3, -4, -20, 14, -22, -18, 2, 1, -50, 6, -27, 36, -1, -75, -16, 18, -11, 6, -56, 20, -17, -39, 23, -50, -28, 13, -11, 24, 22, -66, 5, 27, 3, 7, -27, 30, -51, 4, -2, -23, -26, 6, -3, 23, -10, -50, 29, -2, -18, 13, -64, 4, -40, -29, 0, -5, -6, -18, -10, 22, 15, -51, 2, 25, -2, 9, -58, 14, -38, -40, 8, -49, -37, -38, 14, 18, -12, -37, -23, -1, 23, 41, -92, 35, -28, -60, -8, -6, -39, 1, 1, 47, -29, -45, 
  -29, 6, 35, 31, -22, -70, -4, 30, 1, -19, 24, 25, -57, -28, -7, 9, 23, 4, 37, -10, 0, -31, 4, 41, 24, 9, 52, -62, -22, -4, -58, 27, -33, -1, 27, 33, 3, -19, -5, 34, -1, 2, 41, -7, -61, -24, 11, 7, 19, 2, 14, 2, 13, -57, -11, 27, 6, -13, 27, -19, -13, -8, -4, 11, -32, 7, 20, -20, 19, -76, -3, 45, 5, -2, 34, -51, -34, -43, -36, 19, -26, 15, 25, 19, 15, -41, 8, 33, -11, -23, 25, -53, -67, -63, 43, 24, -3, 5, 16, -17, 13, -61, -5, 32, 20, -4, 22, -49, -47, -27, -49, 7, -52, -8, 31, 6, -5, -63, 22, 35, 11, 0, 27, -58, -60, -14, -19, 33, 37, -23, 7, -38, -3, -85, 10, 33, 28, -22, 7, -98, -37, -27, -13, 27, 30, -5, 11, -25, 4, -57, -8, 34, -2, -13, 14, -51, -33, -16, -17, 14, 6, 57, 29, -27, 18, -88, 43, 32, 42, 9, 13, -114, -57, -4, -65, 20, 9, -13, 22, -19, 17, -101, -10, 32, 14, 12, 24, -55, -54, 3, -33, 7, 60, -6, 24, 9, 7, -72, -10, 29, 16, -13, 45, -62, -89, -22, -39, 13, -9, -27, 7, -35, -13, -71, 31, 35, 11, -9, 26, -65, -15, 1, -56, 4, -1, -16, 12, -23, 13, -66, -1, 37, 32, -22, 27, -37, -28, -8, -3, 28, 28, -13, 14, -40, 11, -45, 9, 27, 32, -1, 25, -64, -49, -11, -56, 1, 13, -56, 28, -44, -5, -25, -31, 12, 25, 0, 20, -38, -28, 4, 15, 8, 9, -31, 24, 14, -13, -38, -11, 35, 18, 9, 28, -28, -56, 22, -20, 22, -3, -32, 9, -4, 14, -75, 17, 22, 57, 27, 24, -73, -30, -3, 11, 13, -15, -22, 32, 23, -10, -30, 14, 28, 41, -12, 38, -61, -12, 20, 3, 3, -18, -23, 29, -14, 4, -49, 2, 5, 16, -20, 29, -35, -74, 15, 52, 16, -1, -3, 12, -38, -4, -65, 3, 8, 17, 19, 24, -64, 17, 32, 16, 27, -13, -3, 16, 4, -8, 22, -13, 50, 16, 16, 40, -30, 9, 8, 31, 19, -4, -16, 0, -41, -4, -39, 2, 18, 6, 32, 19, -3, -26, 6, -20, 8, 22, -20, 60, 8, -4, -73, -7, 25, 32, -22, 35, -14, -52, -10, 34, 26, 
  -54, -4, -26, -28, 12, -12, 16, -35, -24, 21, -20, -48, -62, -90, 34, -11, -14, 7, 3, -20, 7, -63, 22, -25, -3, 11, -32, -24, 21, -94, 40, 1, -24, 58, -10, -12, 40, -42, 21, -7, -14, 13, -70, -28, 36, -74, 13, -17, -30, 18, 19, -21, -6, -50, 23, -7, 13, 35, -8, -5, 30, -72, 42, 9, -30, 56, 15, -17, 17, -2, 3, -8, 8, 16, -38, 7, 33, -58, 66, -23, -47, 56, 1, -31, 21, -54, 21, 3, 19, 40, -68, -14, 26, -76, 49, -57, -58, 27, 2, -24, 14, -76, 19, -27, 35, 28, -42, -5, 33, -51, 26, -30, -37, 54, 8, -6, 34, -41, 21, -40, -18, 31, -74, -25, 13, -88, 44, -39, -42, 41, 33, -5, 11, -22, 12, -15, 26, 29, -24, 14, 16, -18, 22, -41, -39, 48, -10, -28, -2, -77, 1, -20, -5, 30, -39, -11, 13, -66, 34, -23, -50, 9, -4, -54, 7, -40, 8, -12, 6, 24, -22, -12, 10, -63, 22, -2, -8, 58, -6, -6, 21, -58, 35, -9, 45, 51, -49, -21, 28, -35, 54, 9, -83, 32, 25, -35, -2, -44, 19, -22, -23, 6, -67, -20, 6, -74, 28, -42, -27, 40, 13, -30, 4, -60, -6, 12, 44, 29, -19, -2, 42, -44, 51, -23, -57, 69, 7, 7, -7, -66, 23, -32, -10, -4, -19, 1, 12, -64, 38, 4, -67, 17, 15, -36, 6, -45, 6, -10, 3, 14, -55, 19, 30, -70, 23, -31, -18, 75, -18, -16, -2, -83, -8, -42, 17, 23, -39, 4, 17, -39, 51, -11, -49, 28, -3, -53, -12, -61, 26, -29, -5, -3, -51, -25, 6, -58, 21, -15, -35, 47, 22, -20, 0, -67, -13, 23, 12, 32, -23, 17, 5, -38, 17, -16, -40, 16, 13, 8, -15, -48, 16, -24, 1, 11, -56, 12, 16, -64, 37, -27, -2, 27, 7, -28, 0, -45, -9, -5, 23, -2, -28, 35, 25, -55, 23, -14, -22, 40, -13, 50, 15, -80, -14, -3, 13, 37, -40, 43, -53, -7, 78, -43, -36, -3, 2, -33, -25, -60, 5, -38, 2, -14, -75, -4, 25, -54, 16, -5, -56, 38, 5, -31, 6, -44, 2, -3, 8, 2, -30, 62, 14, -32, 29, -13, -22, 27, -28, -17, -12, -121, -2, -5, -1, -16, -63, -1, -24, -22, 21, -12, 
  21, -17, -47, -16, 5, 23, -21, 27, 31, 14, -19, 22, 38, 33, -48, -33, -12, -27, -29, -45, 26, 10, -47, 23, -20, 21, -17, 28, -43, 26, -12, -31, 29, -65, -65, -56, 8, 16, -16, 8, 10, 0, -11, -1, -9, 44, -31, -41, 24, -26, -48, -66, 12, 15, -28, 3, -18, -39, -12, -9, 19, 49, -9, -29, 7, -46, -77, -37, 14, 8, -47, 5, 2, 20, 36, -15, 15, 47, -31, -43, 22, -46, -73, -87, 6, 16, -50, 16, -20, -13, 40, 1, 7, 48, -9, -38, 7, -43, -96, -25, 20, 10, -26, 20, -45, 0, 10, 5, 19, 20, 19, -30, 44, -36, -70, -93, 31, 9, -42, 20, 13, -9, 33, 2, -13, 32, -10, -31, 34, -22, -61, -54, 4, 17, -36, 14, -24, -8, 7, 9, 12, 28, 23, -38, -15, -53, -80, -44, 36, 22, -14, 15, 13, 21, 15, -25, 11, 21, -22, -21, 4, -16, -48, -63, 10, 12, -49, 16, -19, 2, -20, 0, 34, 21, -1, -32, 0, -30, -44, -55, 19, 4, -32, 4, -14, -21, -24, -3, 14, 32, -2, -25, 18, -21, -55, -77, 31, 11, -19, 17, -2, 2, 17, -33, 34, 32, -34, -43, -7, 31, -59, -69, 23, 12, -56, 28, -15, 9, -9, 6, -5, 41, 3, -45, 6, -22, -55, -60, 17, 11, -31, 21, -34, -16, -5, -7, 10, 25, -10, -38, 10, 32, -22, -40, 26, 2, -4, 40, -21, -3, -16, -16, 5, 29, -24, -46, -9, -12, -24, -25, 25, 7, -3, 41, -48, 22, -7, -1, 20, 16, -19, -39, 12, 19, -29, -28, 26, 14, -41, 28, -57, -6, 15, -24, 10, 28, -53, -14, 12, -36, -19, -4, 15, 23, -10, 32, -44, 13, -22, -27, -6, 27, -36, -42, 6, 20, -13, -8, 26, 24, -39, 43, -4, 4, 31, -10, 26, 31, -28, -28, 3, 8, -16, -50, 26, 6, -8, 39, -9, -19, -43, -2, 47, 24, -19, -44, 14, -47, -2, -33, 25, 22, -19, 21, -14, 10, 33, 6, -1, 4, -10, -22, -31, 36, -17, 20, 28, 24, -28, 37, 15, -21, 22, 17, 13, 37, 1, -24, 2, -11, 6, -13, 18, 24, 12, 36, 25, 14, -4, -13, 0, 21, -4, -20, -27, 43, -17, -48, 14, 25, 7, 42, 26, 8, 29, -21, 37, 21, 6, 0, 
  -65, 12, 8, 11, 7, 15, -63, 2, -36, 0, 11, 12, 15, -18, 7, -36, -64, -9, 28, 7, 8, 17, -19, -11, -48, 9, -100, -41, 38, -13, -9, -12, -11, 4, 56, 17, -17, 15, -14, -14, -73, 50, 7, -23, 22, -35, -26, -72, -65, -17, 36, 13, 20, 24, -12, 12, -58, -15, -73, -23, 18, -50, -60, -84, -38, -40, 31, 32, 16, 6, 8, 15, -113, 44, -23, -59, -3, -1, -31, -50, -37, 24, 37, 42, 5, 38, -26, 21, -22, -24, -36, 2, -9, -44, 3, -66, 13, -20, 35, 36, 11, -25, -31, -2, -33, 14, -15, -32, 26, -41, -4, -65, -20, -5, 31, 43, 16, -4, -34, 29, -50, 2, -18, -2, 37, -10, 3, -90, -40, -53, 46, 40, 29, 9, -25, -13, -48, 40, -6, 18, 28, -12, -49, -51, -33, -7, 52, 20, 6, 18, -5, 3, -19, 30, -10, 28, 13, -20, 21, -50, -30, -39, 26, 45, 9, 15, 2, 6, -48, 44, -28, 19, -7, -10, 8, -68, -55, 12, 46, 55, 29, -15, -23, -16, -17, 15, -14, -18, -2, -22, -4, -51, -50, -3, 33, 17, 13, -2, -17, -2, -32, 16, -12, -19, -14, -17, -2, -53, -28, -45, 31, 51, 19, -6, -33, -18, -63, -6, 6, -15, -4, -38, -20, -84, -61, -27, 13, 41, 18, 5, -8, -27, -21, -1, -40, -11, 20, -41, -51, -80, -44, 21, 15, 34, 5, -12, -62, -13, -56, 9, -14, 13, 5, -10, 15, -87, -66, -42, 39, 42, 41, -4, 22, 8, -35, 4, -31, 10, -3, -34, -9, -48, -28, -7, 22, 15, 18, -21, -43, -6, -54, 1, 6, 13, 33, -17, 12, -40, -72, -26, 4, 31, 16, -33, -39, -22, -22, -1, 8, 21, 41, -32, -67, -52, -15, -88, -9, 31, 13, -38, -14, 29, -9, -7, -19, 5, -20, -16, -14, -25, -27, -16, -21, 13, -12, 0, -24, 23, -12, 14, -15, -45, 12, -22, -34, -18, -40, 18, 21, -6, 9, 0, 47, 15, 1, -37, -46, -31, 3, -60, 30, 12, -16, 32, 13, -47, 28, -16, -3, 15, -10, 9, -37, -7, 18, -57, -12, -14, 12, -16, 27, 22, 16, -4, -19, -38, 14, 8, -29, -18, -31, -76, -44, -3, 15, -25, -13, 14, 11, 14, 30, -5, -4, -21, -2, -12, 24, -75, -14, 7, 
  29, -6, -23, -43, 13, -26, 16, 8, -34, 19, -53, -77, -20, 22, -10, 24, 16, 23, -39, -6, 14, -10, 41, -18, -9, -1, -52, 10, 21, 2, 14, 23, 26, -8, -23, -56, -2, -5, 22, -18, -19, 10, -37, -5, 8, 11, -23, 27, 37, 18, -26, 1, 19, -18, 49, -18, -10, 18, -48, -40, -38, 18, -1, 35, 55, 21, -27, -23, 29, 12, 26, -21, -40, 14, -87, -4, -8, 8, -51, 36, 47, 7, -25, -23, 9, -9, 38, -21, -23, 30, -87, -10, -34, 34, -25, 32, 37, 8, -14, -16, 21, 13, 30, -14, -83, 13, -91, -13, -23, -14, -9, 20, 25, 5, -26, -10, 10, 17, 33, -20, -46, 44, -81, -9, -33, 10, -38, 25, 13, 5, -30, -8, 26, 9, 32, -7, -40, 21, -54, -13, -62, 2, -14, 42, 19, -10, -25, -41, 11, -6, 43, -12, -51, 27, -76, -5, 0, 8, -27, 31, 39, -11, -24, 8, 26, 7, 22, -11, -52, 20, -89, -20, -75, 16, 12, 36, 42, -1, -26, -9, 4, 2, 10, -14, -57, 21, -62, -25, -16, -19, 4, 19, 35, 8, -35, 3, 30, -6, 24, 0, 6, 25, -82, -15, -31, 11, 3, 39, 32, 0, -5, 7, 10, -1, 41, 1, -53, 18, -44, -37, -60, 10, 2, 24, 44, 8, -6, 0, -7, 4, 17, -14, -48, 22, -78, -52, 20, -23, -23, 14, 31, -1, -11, 14, -1, -25, 49, -10, -40, 29, -66, -36, -70, 17, 32, 24, 23, -18, -18, -20, -14, -25, 29, -27, -34, 10, -81, -30, -29, -5, -32, 24, 35, -24, -25, 41, 8, -19, 47, -35, -40, 29, -56, -6, -18, 3, 2, 42, 31, -1, -12, -1, 4, 3, 34, -3, -57, 24, -70, -40, -27, 3, -13, 42, 28, -4, -1, -11, 9, 56, 31, -11, -53, 26, -99, -4, 11, -6, -8, 47, 40, 2, -1, 66, 10, -6, 45, -1, -45, 28, -35, -4, -51, 8, -1, 24, 39, -7, 5, -3, 9, 7, 38, 16, -35, 7, -53, 15, -26, -5, -26, 31, 54, -13, -11, 41, 7, -7, 15, -6, -36, 25, -29, -6, -4, 10, 15, 17, 34, -24, 9, 31, 6, -1, 20, 2, -17, -3, -47, -40, -51, 7, 32, 29, 36, -15, -50, 4, 12, -11, 13, 2, -27, 32, -66, -29, 1, 18, -12, 31, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 8,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0085785044357180595, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -285, -2089, -3625, -1161, 345, -212, -340, -1983, -1460, -1614, -815, -2264, 321, -763, -1765, -443, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00039449386531487107, 0.00028337497496977448, 0.0001815204304875806, 0.00052539474563673139, 0.00018235052993986756, 0.00024614532594569027, 0.00018059890135191381, 0.00023194217646960169, 0.00036505190655589104, 0.000202362090931274, 0.00042994820978492498, 0.00018708102288655937, 0.00029479962540790439, 0.00041097679059021175, 0.00022590608568862081, 0.00033232170972041786, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -49,3,59,15,-78,39,-20,-4, -81,-1,-2,-19,-127,10,-26,-38, -91,-6,37,24,-110,-1,-28,-55, 
  /* [1][0][][] */ 5,21,-127,69,-47,-53,-12,-1, -42,-16,-69,-39,30,-35,31,32, 96,-29,39,-37,-34,-9,-14,13, 
  /* [2][0][][] */ -98,-22,-4,-12,36,-63,61,20, -29,-55,8,56,45,-89,-20,114, -77,-33,45,-80,21,-83,127,-33, 
  /* [3][0][][] */ 1,-96,15,-70,52,-25,-4,6, 16,-127,0,-41,-8,-32,9,14, 0,-106,-24,-15,28,-23,9,21, 
  /* [4][0][][] */ 46,-33,-119,-61,-34,53,34,-77, -9,-40,-120,-51,-86,13,-10,-3, 66,-51,-5,-35,-70,127,8,53, 
  /* [5][0][][] */ -124,83,-43,45,-73,-88,-62,-20, -127,-35,-49,15,-71,-82,-92,-40, -103,109,-65,38,-72,-34,-29,-12, 
  /* [6][0][][] */ 87,-118,57,-48,-83,-110,-25,20, -6,-127,84,-45,-115,-62,1,98, -5,-127,-31,-9,-121,100,-10,11, 
  /* [7][0][][] */ -17,-2,-127,-72,-1,-3,123,-84, -7,-15,-100,-65,-22,5,7,-111, 0,-24,-78,-79,-33,32,73,-77, 
  /* [8][0][][] */ -29,-82,-13,93,7,-11,14,-8, -27,-127,-9,18,-12,-11,-14,22, -2,-93,-4,3,13,-40,-33,19, 
  /* [9][0][][] */ 2,-113,-30,0,-13,42,14,-7, 11,-97,63,-16,13,127,-8,-7, 22,-66,-6,-8,10,-42,-33,50, 
  /* [10][0][][] */ -86,-3,-14,22,-51,6,-75,47, -85,3,-18,24,-69,-3,-127,-8, -94,1,-16,26,-58,-25,-82,63, 
  /* [11][0][][] */ -108,66,-35,96,117,-47,-28,-53, -35,-6,-60,1,89,-127,-15,-38, -77,4,-93,118,-32,-103,-37,-16, 
  /* [12][0][][] */ -33,-12,-45,105,-105,-12,4,15, -2,10,-127,-33,-42,33,14,-39, 10,17,-67,-51,-9,-35,-6,-72, 
  /* [13][0][][] */ -24,22,26,-53,18,-31,-99,-29, -3,2,10,-84,-30,-48,-110,-20, -20,45,60,-74,2,-86,-127,6, 
  /* [14][0][][] */ 76,-22,6,-54,-12,-38,-5,-112, -43,-18,-2,-41,90,-37,-6,-90, 78,-22,-29,127,-12,-4,4,-9, 
  /* [15][0][][] */ -13,-82,46,-3,-110,8,-18,50, -14,-79,5,-22,-127,0,-35,-5, -36,-69,46,-29,-120,23,-32,63, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0087177781388163567, 0.0062622018158435822, 0.0040113548748195171, 0.01161050982773304, 0.0040296986699104309, 0.0054394770413637161, 0.0039909901097416878, 0.0051256068982183933, 0.0080671506002545357, 0.0044719269499182701, 0.0095012709498405457, 0.0041342363692820072, 0.0065146707929670811, 0.0090820286422967911, 0.0049922172911465168, 0.0073438580147922039, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -1474, -2971, -2089, -2484, -2814, -1806, -2292, -4968, };
const TfArray<8, float> quant10_scale = { 8, { 0.00037369117490015924, 0.00031906645745038986, 0.00031781458528712392, 0.00039133583777584136, 0.00033312835148535669, 0.00032421521609649062, 0.00024839930119924247, 0.00023279404558707029, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*13] = { 
  /* [0][0][][] */ 55,18,-38,15,-43,39,-19,-19,-127,11,27,-14,29, -100,7,51,-52,-89,-35,-33,10,109,9,25,-6,-17, -26,-17,12,-37,27,65,-40,-16,38,-92,-13,-29,36, 
  /* [1][0][][] */ -91,-16,-28,67,-52,94,-83,-32,0,34,1,13,-66, -127,37,-11,35,-8,60,-59,10,-13,6,5,27,-56, -94,1,-11,99,-18,44,-70,3,3,5,0,36,-104, 
  /* [2][0][][] */ 54,44,-84,-6,-50,11,41,-92,29,3,79,-110,6, 0,-2,-20,-11,-58,-4,-44,-34,28,-21,53,-52,-18, 12,16,-76,-45,-63,24,-2,-47,112,-56,121,-127,-7, 
  /* [3][0][][] */ -48,-10,-29,-58,78,-40,74,12,31,-8,10,-10,7, 55,-8,-25,127,68,-12,45,-32,37,-24,42,16,56, 37,23,-12,1,65,18,55,14,20,19,-22,14,-16, 
  /* [4][0][][] */ 36,-24,-22,2,-103,24,-20,26,-95,-16,-32,72,-30, 36,-11,115,-27,64,22,-40,-1,-101,22,18,-80,22, -35,-55,127,-40,-91,3,22,19,-54,-21,2,7,-38, 
  /* [5][0][][] */ -124,34,9,-26,-38,31,-17,-7,47,-36,-8,65,-11, -3,-14,-3,-127,-46,-2,61,-50,68,22,11,-8,-17, 101,49,2,-4,-41,22,29,-37,85,-39,7,9,4, 
  /* [6][0][][] */ -13,127,-65,28,61,-120,-7,-115,-86,-102,-76,18,-66, -91,53,-97,41,21,21,21,-30,-53,0,40,37,27, -39,97,-17,-45,-35,-123,90,-52,-57,26,-54,94,-34, 
  /* [7][0][][] */ -2,19,21,41,34,-11,24,-27,63,-65,94,-109,13, -12,1,51,-17,127,-78,19,-39,78,-85,77,-23,-60, 11,19,28,38,49,-46,-52,-56,59,-44,104,-31,-49, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,13 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0065813991241157055, 0.0056193559430539608, 0.0055973082780838013, 0.0068921544589102268, 0.0058670118451118469, 0.0057100350968539715, 0.0043747755698859692, 0.0040999376215040684, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,13 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.045251652598381042, } };
const TfArray<1, int> quant13_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.035678748041391373, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,8 } };
const TfArray<1, float> quant21_scale = { 1, { 0.19965174794197083, } };
const TfArray<1, int> quant21_zero = { 1, { 36 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1296), (TfLiteIntArray*)&g0::tensor_dimension0, 1287, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 3200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension6, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 312, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 1287, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1296), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_972028_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_972028_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_972028_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_972028_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_972028_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
