; Node 3 — ESP32 Spotlight (đèn rọi pan/tilt bám người) — GIAI ĐOẠN 4
[platformio]
extra_configs = secrets.ini

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    ${secrets.build_flags}
    -D CORE_DEBUG_LEVEL=3
    -I ../common/include
    -Wall

lib_deps =
    madhephaestus/ESP32Servo@^3.0.5
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
